Add gradetool support (#1037)
* Add gradetool support

* Address comments 1

* experiment with the image

diff --git a/.github/workflows/pre-main.yaml b/.github/workflows/pre-main.yaml
--- a/.github/workflows/pre-main.yaml
+++ b/.github/workflows/pre-main.yaml
@@ -13,6 +13,8 @@ env:
   TNF_IMAGE_TAG: unstable
   OCT_IMAGE_NAME: testnetworkfunction/oct
   OCT_IMAGE_TAG: latest
+  GRADETOOL_IMAGE_NAME: testnetworkfunction/gradetool
+  GRADETOOL_IMAGE_TAG: latest
   TNF_CONTAINER_CLIENT: docker
   TNF_NON_INTRUSIVE_ONLY: false
   TNF_ALLOW_PREFLIGHT_INSECURE: false
@@ -163,7 +165,7 @@ jobs:
           totalCoverage=`UNIT_TEST='true' cat cover.out.tmp | grep -v "_moq.go" > cover.out; go tool cover -func=cover.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
           echo "Current test coverage : $totalCoverage %"
           if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
-              echo "OK"
+              echo OK
           else
               echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
               echo "Failed"
@@ -203,8 +205,8 @@ jobs:
       - name: Update the CNF DB
         run: |
           docker pull ${REGISTRY}/${OCT_IMAGE_NAME}:${OCT_IMAGE_TAG}
-          mkdir -p ${GITHUB_WORKSPACE}/offline-db
-          docker run -v ${GITHUB_WORKSPACE}/offline-db:/tmp/dump:Z --env OCT_DUMP_ONLY=true ${REGISTRY}/${OCT_IMAGE_NAME}:${OCT_IMAGE_TAG}
+          mkdir -p "${GITHUB_WORKSPACE}"/offline-db
+          docker run -v "${GITHUB_WORKSPACE}"/offline-db:/tmp/dump:Z --env OCT_DUMP_ONLY=true ${REGISTRY}/${OCT_IMAGE_NAME}:${OCT_IMAGE_TAG}
 
       - name: Install ginkgo
         run: make install-tools
@@ -244,6 +246,33 @@ jobs:
             cnf-certification-test/claimjson.js
             cnf-certification-test/results.html
             cnf-certification-test/tnf-execution.log
+
+      # - name: Clone the gradetool repository
+      #   uses: actions/checkout@v3
+      #   with:
+      #     repository: test-network-function/gradetool
+      #     path: gradetool
+      
+      # - name: Run gradetool on the claim.json
+      #   run: |
+      #     make build
+      #     ./gradetool -p "${GITHUB_WORKSPACE}"/generated_policy.json -o "${GITHUB_WORKSPACE}"/results.txt -r "${GITHUB_WORKSPACE}"/cnf-certification-test/claim.json
+      #   working-directory: gradetool
+
+      - name: Run gradetool on the claim.json
+        run: |
+          docker pull ${REGISTRY}/${GRADETOOL_IMAGE_NAME}:${GRADETOOL_IMAGE_TAG}
+          docker run -v "${GITHUB_WORKSPACE}"/generated_policy.json:/policy.json -v "${GITHUB_WORKSPACE}"/cnf-certification-test/claim.json:/claim.json ${{ env.REGISTRY }}/${{ env.GRADETOOL_IMAGE_NAME }}:${{ env.GRADETOOL_IMAGE_TAG }} -p /policy.json -o results.txt -r /claim.json > "${GITHUB_WORKSPACE}"/results.txt
+
+      - name: Check that their are 0 failed tests in the gradetool results
+        run: |
+          if $(jq '.[] | .Fail | length' "${GITHUB_WORKSPACE}"/results.txt | grep -q 0); then
+            echo OK
+          else
+            echo "Gradetool has found failing tests in the following:"
+            jq '.[] | .Fail | .[].id' "${GITHUB_WORKSPACE}"/results.txt
+            exit 1
+          fi
 
       - name: 'Test: Run preflight specific test suite'
         run: TNF_LOG_LEVEL=${TNF_SMOKE_TESTS_LOG_LEVEL} ./run-cnf-suites.sh -l "preflight"
@@ -328,6 +357,33 @@ jobs:
             ${{ env.TNF_OUTPUT_DIR }}/claimjson.js
             ${{ env.TNF_OUTPUT_DIR }}/results.html
             ${{ env.TNF_OUTPUT_DIR }}/tnf-execution.log
+
+      # - name: Clone the gradetool repository
+      #   uses: actions/checkout@v3
+      #   with:
+      #     repository: test-network-function/gradetool
+      #     path: gradetool
+    
+      # - name: Run gradetool on the claim.json
+      #   run: |
+      #     make build
+      #     ./gradetool -p "${GITHUB_WORKSPACE}"/generated_policy.json -o "${GITHUB_WORKSPACE}"/results.txt -r ${{ env.TNF_OUTPUT_DIR }}/claim.json
+      #   working-directory: gradetool
+
+      - name: Run gradetool on the claim.json
+        run: |
+          docker pull ${REGISTRY}/${GRADETOOL_IMAGE_NAME}:${GRADETOOL_IMAGE_TAG}
+          docker run -v "${GITHUB_WORKSPACE}"/generated_policy.json:/policy.json -v ${{ env.TNF_OUTPUT_DIR }}/claim.json:/claim.json ${{ env.REGISTRY }}/${{ env.GRADETOOL_IMAGE_NAME }}:${{ env.GRADETOOL_IMAGE_TAG }} -p /policy.json -o results.txt -r /claim.json > "${GITHUB_WORKSPACE}"/results.txt
+  
+      - name: Check that their are 0 failed tests in the gradetool results
+        run: |
+          if $(jq '.[] | .Fail | length' "${GITHUB_WORKSPACE}"/results.txt | grep -q 0); then
+            echo OK
+          else
+            echo "Gradetool has found failing tests in the following:"
+            jq '.[] | .Fail | .[].id' "${GITHUB_WORKSPACE}"/results.txt
+            exit 1
+          fi
 
       - name: 'Test: Run Preflight Specific Smoke Tests in a TNF container'
         run: TNF_LOG_LEVEL=${TNF_SMOKE_TESTS_LOG_LEVEL} ./run-tnf-container.sh ${{ env.TESTING_CMD_PARAMS }} -l "preflight"
